name: network_tools_flutter
description: Extended features of network_tools package for flutter framework supporting iOS and Android
version: 1.0.5
issue_tracker: https://github.com/osociety/network_tools_flutter/issues
repository: https://github.com/osociety/network_tools_flutter

environment:
  sdk: ">=3.2.0 <4.0.0"

platforms:
  android:
  ios:
  linux:
  macos:
  windows:
  
topics:
  - network
  - ping
  - arp
  - port
  - scanner

funding:
  - https://liberapay.com/OpenSociety/donate
  - https://ko-fi.com/fs0c13ty

dependencies:
  flutter:
    sdk: flutter
  
  # Multi-platform network ping utility.
  dart_ping: ^9.0.1
  dart_ping_ios: ^4.0.2
  fake_http_client: ^1.0.0
  flutter_isolate: ^2.0.4
  # Debugging and error logging.
  logging: ^1.2.0
  # Deal with internationalized/localized messages and more.
  intl: ^0.18.1
  # network_tools: ^4.0.3
  network_tools:
    path: "../network_tools" 
    # git:
    #  url: "https://github.com/guyluz11/network_tools.git"
    #  ref: "adding_ios_support"
  path_provider: ^2.1.1
  universal_io: ^2.2.2
  nsd: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  # Standalone generator and watcher for Dart 
  build_runner: ^2.4.7

flutter:
