name: Publish plugin

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for authentication using OIDC
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Java JDK
        uses: actions/setup-java@v4.5.0
        with:
          distribution: temurin
          java-version: "17"

      - name: Flutter action
        uses: subosito/flutter-action@v2.16.0
        with:
          channel: stable

      - name: Flutter version
        run: flutter --version

      - name: Download pub dependencies
        run: flutter pub get
        
      - name: Upgrade pub dependencies
        run: flutter pub upgrade

      - name: Run analyzer
        run: flutter analyze --fatal-infos

      - name: Run tests
        run: flutter test

      - name: Check Publish Warnings
        run: flutter pub publish --dry-run

      - name: Publish to pub.dev
        run: dart pub publish -f