name: Publish plugin

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: "17"

      - name: Flutter action
        uses: subosito/flutter-action@v2.8.0
        with:
          channel: stable

      - name: Flutter version
        run: flutter --version

      - name: Cache pubspec dependencies
        uses: actions/cache@v3.0.7
        with:
          path: |
            ${{ env.FLUTTER_HOME }}/.pub-cache
            **/.packages
            **/.flutter-plugins
            **/.flutter-plugin-dependencies
            **/.dart_tool/package_config.json
          key: build-pubspec-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            build-pubspec-

      - name: Cache build runner
        uses: actions/cache@v2
        with:
          path: |
            **/.dart_tool
            **/*.g.dart
            **/*.mocks.dart
            **/*.config.dart
          key: build-runner-${{ hashFiles('**/asset_graph.json', '**/*.dart', '**/pubspec.lock', '**/outputs.json') }}
          restore-keys: |
            build-runner-

      - name: Download pub dependencies
        run: flutter pub get
        
      - name: Upgrade pub dependencies
        run: flutter pub upgrade

      - name: Run analyzer
        run: flutter analyze --fatal-infos

      - name: Run tests
        run: flutter test --coverage

      - name: Check Publish Warnings
        run: flutter pub publish --dry-run

  publish:
    needs: 'test'
    permissions:
      id-token: write # Required for authentication using OIDC
    uses: git-elliot/setup-dart/.github/workflows/publish.yml@main # Added build_runner step
    with:
      environment: 'pub.dev'